version: '3.4'

services:
  api:
    container_name: dictionary
    build:
      context: .
      dockerfile: compose/dictionary/Dockerfile
    working_dir: /app/dictionary
    command: python ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"