# Generated by Django 4.1.3 on 2023-01-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Word frequency rank"
                    ),
                ),
                (
                    "spelling",
                    models.CharField(max_length=32, verbose_name="Word spelling"),
                ),
                ("origin", models.CharField(max_length=64, verbose_name="Word origin")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("명사", "Noun"),
                            ("대명사", "Pronoun"),
                            ("수사", "Number"),
                            ("동사", "Verb"),
                            ("형용사", "Adjective"),
                            ("관형사", "Determiner"),
                            ("부사", "Adverb"),
                            ("감탄사", "Interjection"),
                            ("조사", "Post-position"),
                        ],
                        max_length=3,
                        verbose_name="Word's part of speech",
                    ),
                ),
                (
                    "word_class",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        verbose_name="Word's class",
                    ),
                ),
            ],
        ),
    ]
