# Generated by Django 4.1.3 on 2023-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="meading",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Meaning"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="origin",
            field=models.CharField(max_length=64, verbose_name="Origin"),
        ),
        migrations.AlterField(
            model_name="word",
            name="rank",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Frequency rank"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="spelling",
            field=models.CharField(max_length=32, verbose_name="Spelling"),
        ),
        migrations.AlterField(
            model_name="word",
            name="type",
            field=models.CharField(
                choices=[
                    ("명사", "Noun"),
                    ("대명사", "Pronoun"),
                    ("수사", "Number"),
                    ("동사", "Verb"),
                    ("형용사", "Adjective"),
                    ("관형사", "Determiner"),
                    ("부사", "Adverb"),
                    ("감탄사", "Interjection"),
                    ("조사", "Post-position"),
                ],
                max_length=3,
                verbose_name="Part of speech",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word_class",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")],
                max_length=1,
                verbose_name="Class",
            ),
        ),
    ]
