# Generated by Django 4.1.3 on 2023-01-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0002_word_meading_alter_word_origin_alter_word_rank_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="meading",
            new_name="meaning",
        ),
    ]
