# Generated by Django 4.1.3 on 2023-01-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0004_remove_word_word_class_alter_word_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("명사", "Noun"),
                    ("대명사", "Pronoun"),
                    ("수사", "Number"),
                    ("동사", "Verb"),
                    ("형용사", "Adjective"),
                    ("관형사", "Determiner"),
                    ("부사", "Adverb"),
                    ("감탄사", "Interjection"),
                    ("조사", "Post-position"),
                ],
                max_length=3,
                null=True,
                verbose_name="Part of speech",
            ),
        ),
    ]
