# Generated by Django 4.1.3 on 2023-01-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0005_alter_word_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="word",
            name="type",
        ),
    ]
